name: slicethendice
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7919484442099929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee752f'
    - '#cb2a2e'
    - '#efad94'
    - '#f9ddd3'
  brandStrength: 0.8332195219118148
  lightness: 0.9252429106272757
  saturation: 0.16099020978435874
  rhythmicContrast: 0.7280043272767216
purpose: []
